name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Generate main build number
      id: buildnumbermain
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.GIT_TOKEN }}
        prefix: ${{ secrets.MAIN_APP_PREFIX }}
      
    - name: Build, tag, and push main image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ steps.buildnumbermain.outputs.build_number }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        touch testing.txt
        ls
        
    - name: Logout from Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
      
    - name: deploy to development
      if: success()
      run: |
        echo $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      
  approve:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Approve
      id: approve
      run: |
        echo "Please Approve to Deploy to Staging"
        echo "* [Approve](#approve)"
        echo "* [Reject](#reject)" 
        
  deploy_to_staging:
    needs: approve
    if: steps.approve.outputs.approved == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Staging
      run: |
        echo "deploy_to_staging - YES"
        ls
        
  approve_to_prod:
    needs: deploy_to_staging
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Staging
      run: |
        echo "deploy_to_prod - YES"
        ls
     
