name: Build and Deploy BOPO Multi Enviroments
on:
#   pull_request:
#       branches:
#         - main
#         - development
#         - stage
   push:
      branches:
        - main
        - development
        - stage
        
jobs:
  build:
#     if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Generate main build number
      id: buildnumbermain
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.GIT_TOKEN }}
        prefix: ${{ secrets.MAIN_APP_PREFIX }}
      
    - name: Build, tag, and push main image to Amazon ECR
      id: build_image_tag_push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ steps.buildnumbermain.outputs.build_number }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Get repo url & image
      id: get_image
      run: |
        REPO_URL=$(aws ecr describe-repositories --repository-names bopo --query "repositories[0].repositoryUri" --output text)
        IMAGE_LIST=$(aws ecr list-images --repository-name bopo)
        IMAGE_NAME=$(echo $IMAGE_LIST | jq '.imageIds[-1].imageTag' -r)
        echo $REPO_URL:$IMAGE_NAME
        echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        
    - name: Logout from Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
      
    - name: deploy to development
      if: success()
      run: |
        echo ${{ env.REPO_URL }}/${{ env.IMAGE_NAME }}
#      kubectl set image deployment/my-deployment my-container=${{ env.REPO_URL }}/${{ env.IMAGE_NAME }}
             
  deploy-stage:
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo stage!

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get repo url & image
        run: |
          REPO_URL=$(aws ecr describe-repositories --repository-names bopo --query "repositories[0].repositoryUri" --output text)
          IMAGE_LIST=$(aws ecr list-images --repository-name bopo)
          IMAGE_NAME=$(echo $IMAGE_LIST | jq '.imageIds[-1].imageTag' -r)
          echo $REPO_URL:$IMAGE_NAME
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Logout from Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

      - name: deploy to development
        if: success()
        run: |
          echo ${{ env.REPO_URL }}/${{ env.IMAGE_NAME }}
       #      kubectl set image deployment/my-deployment my-container=${{ env.REPO_URL }}/${{ env.IMAGE_NAME }}
       
  deploy-main:
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Production!

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get repo url & image
        run: |
          REPO_URL=$(aws ecr describe-repositories --repository-names bopo --query "repositories[0].repositoryUri" --output text)
          IMAGE_LIST=$(aws ecr list-images --repository-name bopo)
          IMAGE_NAME=$(echo $IMAGE_LIST | jq '.imageIds[-1].imageTag' -r)
          echo $REPO_URL:$IMAGE_NAME
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Logout from Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

      - name: deploy to development
        if: success()
        run: |
          echo ${{ env.REPO_URL }}/${{ env.IMAGE_NAME }}
       #      kubectl set image deployment/my-deployment my-container=${{ env.REPO_URL }}/${{ env.IMAGE_NAME }}
   
